[package]
name = "totpvault-gui"
version = "0.1.0"
edition = "2021"
authors = ["Grant Foudree <gfoudree@protonmail.com>"]

[dependencies]
relm4 = "0.9.1"
relm4-components = "0.9.1"
udev = "0.9.1"


totpvault-lib = { path = "../totpvault-lib" }
env_logger = "0.11.5"
log = "0.4.22"

[build-dependencies]
glib-build-tools = "0.17.10"
