[package]
name = "totpvault-lib"
version = "0.1.0"
edition = "2021"

[dependencies]
data-encoding = "2.6.0"
serde = { version = "1.0.215", features = ["derive"] }
zeroize = { version = "1.8.1", features = ["zeroize_derive"] }

[lib]
path = "src/lib.rs"
